### ISSUE TITLE
Install suddenly broken...

### ISSUE THREAD

**Issue by Luke-Poeppel** [Luke-Poeppel/treeplotter#35]
```  
Downloading treeplotter-0.4.1.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xd/391x93x10zn4n2z5gb2599mr0000gn/T/pip-install-tdl3cwfw/treeplotter_576bc8a270b042ba8428d59e5a377a87/setup.py'"'"'; __file__='"'"'/private/var/folders/xd/391x93x10zn4n2z5gb2599mr0000gn/T/pip-install-tdl3cwfw/treeplotter_576bc8a270b042ba8428d59e5a377a87/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/xd/391x93x10zn4n2z5gb2599mr0000gn/T/pip-pip-egg-info-z6z0knih
         cwd: /private/var/folders/xd/391x93x10zn4n2z5gb2599mr0000gn/T/pip-install-tdl3cwfw/treeplotter_576bc8a270b042ba8428d59e5a377a87/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xd/391x93x10zn4n2z5gb2599mr0000gn/T/pip-install-tdl3cwfw/treeplotter_576bc8a270b042ba8428d59e5a377a87/setup.py", line 13, in <module>
        with open(os.path.join("treeplotter", "VERSION")) as version:
    FileNotFoundError: [Errno 2] No such file or directory: 'treeplotter/VERSION'
```

**Comment by Luke-Poeppel** [comment]
Fixed in `v0.4.3`. So insane that this error didn't appear until now 🙄
