### ISSUE TITLE
[WinError 3] The system cannot find the path specified

### ISSUE THREAD

**Issue by scottzach1** [Luke-Poeppel/treeplotter#42]
The example in tests fails to run throwing a path error.

System Details:
- Windows 10
- Python 3.9 (venv)
- Installed version: 0.5.0

The example in tests fails to run with the following error:

```python3
from treeplotter.tree import Node, Tree, create_tree_diagram
root = Node(value=1.0, name=None)

child1 = Node(value=0.5, name=None)
child2 = Node(value=1.0, name=None)
child3 = Node(value=3.0, name="A")
root.children = {child1, child2, child3}
root.children

granchild1 = Node(value=0.5, name=None)
granchild2 = Node(value=3.0, name="B")
granchild3 = Node(value=2.0, name="C")
greatgrandchild = Node(value=1.0, name="D")

child1.add_children([granchild1, granchild2])
child2.add_child(granchild3)
granchild1.add_child(greatgrandchild)


tree = Tree(root=root)

create_tree_diagram(
    tree=tree,
    save_path='/Users/{{USER}}/Downloads',  # also fails with `r"C:\\Users\{{USER}}\Downloads"`
    webshot=True,
    verbose=True
)
```

Output (obfuscated):
```
-> Creating directory and writing tree to JSON...
-> Copying templates...
Traceback (most recent call last):
  File "C:\Users\{{USER}}\PycharmProjects\{{PROJECT_NAME}}\main.py", line 42, in <module>
    create_tree_diagram(
  File "C:\Users\{{USER}}\PycharmProjects\{{PROJECT_NAME}}\venv\lib\site-packages\treeplotter\plotter.py", line 180, in create_tree_diagram
    _prepare_docs_and_screenshot(
  File "C:\Users\{{USER}}\PycharmProjects\{{PROJECT_NAME}}\venv\lib\site-packages\treeplotter\plotter.py", line 99, in _prepare_docs_and_screenshot
    for this_file in os.listdir(treant_templates):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\{{USER}}\\PycharmProjects\\{{PROJECT_NAME}}\\venv\\lib\\site-packages\\treeplotter/templates'
```

Pip Freeze
```bash
click==8.0.4
colorama==0.4.4   
Jinja2==3.0.3     
jsonpickle==2.1.0 
MarkupSafe==2.1.0 
treeplotter==0.5.0
Wand==0.6.7
```

**Comment by Luke-Poeppel** [comment]
Thanks for filing this issue, @scottzach1! Pretty sure I know what the problem is. Unfortunately I'm quite busy these days (I'm in my last year of university) and I haven't had much time to work on this project, but I'll get to it as soon as I can! 👍

**Comment by Luke-Poeppel** [comment]
If you'd like to fix it yourself and submit a pull request, I think it should be as simple as changing the second line here: 
https://github.com/Luke-Poeppel/treeplotter/blob/940e08b02d30f69972b0df1a5668f3b2ade02027/treeplotter/plotter.py#L23-L24
to the following: 
```
treant_templates = os.path.join(here, "templates")
```
The current line assumes the Mac file path system, and is therefore inconsistent when being appended to a Windows filepath. Very good catch!

**Comment by ishandutta2007** [comment]
I am getting similar error but the error is not though by python , It is coming from js I think.
```


>>> create_tree_diagram(tree=tree, save_path=mypath, webshot=True, verbose=True)
-> Creating directory and writing tree to JSON...
-> Copying templates...
-> Writing index.html...
-> Writing Treant CSS file...
-> Writing Node CSS file...
-> Running browserify...
-> Creating webshot with R...
The system cannot find the path specified.
Done ✔
'C://Users//hp//Documents//Projects//spx'
>>>

```

I have tried all possible ways of writing path:

```
mypath="C:\\Users\\hp\\Documents\\Projects\\spx"
```
or
```
mypath="C:/Users/hp/Documents/Projects/spx"
```
or
```
mypath="C://Users//hp//Documents//Projects//spx"
```


PS:
I am on Windows 10 and Python 3.8
